name: my_dictionary
description: "My Personal Dictionary"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/new.png
    - assets/images/default.png
    - assets/uploads/
